export const TODOS_ADD_TODO = "TODOS_ADD_TODO";
export const TODOS_TOGGLE_TODO = "TODOS_TOGGLE_TODO";
export const TODOS_DELETE_TODO = "TODOS_DELETE_TODO";
export const TODOS_SET_TODO = "TODOS_SET_TODO";
